"""Static, shareable release report (spec_V3 §8).

The distribution artifact: a Markdown report + a hero PNG generated by one
command, without opening the app. The Markdown is pure and deterministic (no
network); the PNG is best-effort via kaleido (optional dep, local only) — if
kaleido is unavailable the Markdown still builds and the hero can be a manual
screenshot, so this never blocks.
"""

from __future__ import annotations
